name: crm-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - pyodbc
  - pip
  - pip:
    - azure-ai-ml==1.20.0
    - azure-identity==1.18.0
